/**
 * Given an emoji name, return an object contained stats for the emoji, generated by a LLM
 * @param {string} emojiName 
 * @returns {object}
 */

async function generateEmojiInformation(emojiName) {

    const prompt = `Given an emoji name, return only json with the following fields. 
                It has to be themed as a creature, not as an emoji. 
                Note that "dango" refers to the candy on a stick.
                Always use the emoji name as the name of the creature.
                Be more likely to assign a lower tier, but still assign high tiers occasionally.
        

                {
                    tier: The tier you think it is, (common, rare, epic, legendary, mythical) as a number, 1 to 5,
                    health: The health you think it has as an integer, 1 to 100,
                    damage: The damage it does per attack, 0 to 100,
                    bio: Short bio about it without being verbose, don't discuss what it resembles. But make the bio interesting to read.
                }`

    const url = 'https://text.pollinations.ai/';

    try {
        const response = await fetch(`${url}system=${encodeURIComponent(JSON.stringify(prompt))}&prompt=${encodeURIComponent(emojiName)}&json=true`);
        let text = await response.text();
        text = text.match(/\{[\s\S]*\}/)[0];
        return JSON.parse(text);
    } catch (error) {
        return {
            status: null,
            tier: Math.floor(Math.random() * 5) + 1,
            health: Math.floor(Math.random() * 100) + 1,
            damage: Math.floor(Math.random() * 100),
            bio: `A ${emojiName}`
        }
    }
}

module.exports = generateEmojiInformation;