const { getRandomInt } = require('../../utils');

/**
 * Given an emoji name, return an object contained stats for the emoji, generated by a LLM
 * @param {string} emojiName 
 * @returns {object}
 */

async function generateEmojiInformation(emojiName) {

    const prompt = `Given a custom emoji name, return only json with the following fields. 
                    Always use the given name when referring to it, never use your own.
                    Keep each field short, preferrably only two sentences or less.
                    Emojis should not be themed as emojis, but rather as creatures objects, tools, etc.
                    Don't make any assumptions about it beyond the name, and if you don't know what it is then avoid the topic.
                    If you really have no guesses as to what the emoji could represent, make a vague bio and generate a generic ability.

                    {
                        bio: Short bio about it without being verbose, don't discuss what it resembles. But make the bio interesting to read,
                        abilityBio: Short description of an ability it has,
                        abilityName: Ability name
                    }`

    const url = 'https://text.pollinations.ai/';

    const abilities = [
        { abilityName: 'Swift Move', abilityBio: 'Moves slightly faster than usual in short bursts.' },
        { abilityName: 'Calm Focus', abilityBio: 'Improves concentration for a brief moment.' },
        { abilityName: 'Bright Glow', abilityBio: 'Emits a small harmless light.' },
        { abilityName: 'Keen Sense', abilityBio: 'Notices subtle details in the environment.' },
        { abilityName: 'Steady Grip', abilityBio: 'Holds onto objects with extra stability.' },
        { abilityName: 'Light Step', abilityBio: 'Walks quietly and gently.' },
        { abilityName: 'Warm Aura', abilityBio: 'Generates a soft, comforting warmth.' },
        { abilityName: 'Clear Mind', abilityBio: 'Briefly becomes more mentally organized.' },
        { abilityName: 'Gentle Push', abilityBio: 'Applies a small, harmless force to an object.' },
        { abilityName: 'Quick Learn', abilityBio: 'Picks up simple tasks a little faster.' },
        { abilityName: 'Soft Shield', abilityBio: 'Creates a faint, non-damaging barrier around itself.' },
        { abilityName: 'Stable Stance', abilityBio: 'Resists being knocked off balance easily.' },
        { abilityName: 'Fresh Breeze', abilityBio: 'Creates a tiny gust of air.' },
        { abilityName: 'Echo Sense', abilityBio: 'Detects nearby movement through subtle echoes.' }
    ];


    const fallback = abilities[getRandomInt(abilities.length)];
    try {
        const response = await fetch(`${url}system=${encodeURIComponent(JSON.stringify(prompt))}&prompt=${encodeURIComponent(emojiName)}&json=true`);
        let text = await response.text();
        text = text.match(/\{[\s\S]*\}/)[0];
        let json = JSON.parse(text);

        return {
            bio: json.bio ?? `A ${emojiName}!`,
            abilityName: json.abilityName ?? fallback.abilityName,
            abilityBio: json.abilityBio ?? fallback.abilityBio,
            health: getRandomInt(100) + 1,
            damage: getRandomInt(100)
        }
    } catch (error) {
        return {
            bio: `A ${emojiName}!`,
            abilityName: fallback.abilityName,
            abilityBio: fallback.abilityBio,
            health: getRandomInt(100) + 1,
            damage: getRandomInt(100)
        }
    }
}


module.exports = generateEmojiInformation;


